name: 'ecommerce_mart'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_mart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ecommerce_mart:
    staging:
      +materialized: view
    marts:
      +materialized: table
