services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_MULTIPLE_DATABASES: staging, production
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest 
    environment:
      CLICKHOUSE_DB: warehouse
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mypassword
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client interface
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--query", "SELECT 1"]
      interval: 10s
      retries: 5

  airflow-webserver:
    build: ./airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-super-secret-key
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__LOGGING__REMOTE_LOGGING=false
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW_HOME=/opt/airflow
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
      - CLICKHOUSE_DB=warehouse
      - DBT_PROFILES_DIR=/opt/airflow/dbt
      - DBT_PROJECT_DIR=/opt/airflow/dbt
      - DBT_TARGET=dev
      - WAREHOUSE_DB=clickhouse
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/app/data
      - ./dbt:/opt/airflow/dbt
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: bash -c "
      airflow db init &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    build: ./airflow
    depends_on:
      airflow-webserver:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-super-secret-key
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__LOGGING__REMOTE_LOGGING=false
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
      - AIRFLOW_HOME=/opt/airflow
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
      - CLICKHOUSE_DB=warehouse
      - DBT_PROFILES_DIR=/opt/airflow/dbt
      - DBT_PROJECT_DIR=/opt/airflow/dbt
      - DBT_TARGET=dev
      - WAREHOUSE_DB=clickhouse
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/app/data
      - ./dbt:/opt/airflow/dbt
      - airflow_logs:/opt/airflow/logs
    command: airflow scheduler

  python-dev:
    build:
      context: ./python-dev
      dockerfile: Dockerfile
    volumes:
      - ./airflow/dags:/app/dags
      - ./data:/app/data
      - ./python-dev/scripts:/app/scripts
      - ./python-dev/notebooks:/app/notebooks
      - ./dbt:/app/dbt
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
      - CLICKHOUSE_DB=warehouse
      - DBT_PROFILES_DIR=/app/dbt
      - DBT_PROJECT_DIR=/app/dbt
      - DBT_TARGET=dev
    depends_on:
      - clickhouse

volumes:
  postgres_data:
  airflow_logs:
  clickhouse_data: